CREATE TABLE [dbo].[AccountLegalEntityProvider] (
    [AccountLegalEntityId] BIGINT NOT NULL,
    [Ukprn] BIGINT NOT NULL,
    CONSTRAINT PK_AccountLegalEntityProvider PRIMARY KEY CLUSTERED ([AccountLegalEntityId], [Ukprn]),
    CONSTRAINT [FK_AccountLegalEntityProvider_AccountLegalEntities_AccountLegalEntityId] FOREIGN KEY ([AccountLegalEntityId]) REFERENCES [AccountLegalEntities]([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_AccountLegalEntityProvider_Providers_Ukprn] FOREIGN KEY ([Ukprn]) REFERENCES [Providers]([Ukprn])
);
GO

--todo: FK_AccountLegalEntityProvider_Providers_Ukprn isn't generated by EF Core (according to our unit test CheckDatabaseSchemaAgainstEntityFrameworkExpectedSchema)
-- we should get EF Core Tool's 'View DbContext Model DDL SQL' working to check our schema & indexes in greater detail

CREATE NONCLUSTERED INDEX [IX_AccountLegalEntityProvider_Ukprn] ON [dbo].[AccountLegalEntityProvider] ([Ukprn] ASC) INCLUDE ([AccountLegalEntityId]);
GO
