CREATE TABLE [dbo].[Users]
(
    [Id] INT NOT NULL IDENTITY,
    [Ref] UNIQUEIDENTIFIER NOT NULL,
    [Email] VARCHAR(255) NOT NULL,
    [FirstName] NVARCHAR(50) NOT NULL,
    [LastName] NVARCHAR(50) NOT NULL,
    [Created] DATETIME2 NOT NULL,
    [Updated] DATETIME2 NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY NONCLUSTERED ([Ref] ASC),
    CONSTRAINT [AK_Users_Id] UNIQUE CLUSTERED ([Id] ASC) 
)